export default [
  {
    "login": "yxshrraj",
    "id": 86347034,
    "node_id": "MDQ6VXNlcjg2MzQ3MDM0",
    "avatar_url": "https://avatars.githubusercontent.com/u/86347034?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/yxshrraj",
    "html_url": "https://github.com/yxshrraj",
    "followers_url": "https://api.github.com/users/yxshrraj/followers",
    "following_url": "https://api.github.com/users/yxshrraj/following{/other_user}",
    "gists_url": "https://api.github.com/users/yxshrraj/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/yxshrraj/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/yxshrraj/subscriptions",
    "organizations_url": "https://api.github.com/users/yxshrraj/orgs",
    "repos_url": "https://api.github.com/users/yxshrraj/repos",
    "events_url": "https://api.github.com/users/yxshrraj/events{/privacy}",
    "received_events_url": "https://api.github.com/users/yxshrraj/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Yash Raj",
    "company": "Fresher",
    "blog": "yashrajj.netlify.app/",
    "location": "Ranchi",
    "email": null,
    "hireable": null,
    "bio": "CSE UNDERGRAD",
    "twitter_username": null,
    "public_repos": 36,
    "public_gists": 0,
    "followers": 2,
    "following": 3,
    "created_at": "2021-06-23T08:09:56Z",
    "updated_at": "2023-07-24T12:20:34Z"
  }  
];
